### ISSUE TITLE
More complete NoBot scope

### ISSUE THREAD

**Issue by Crazypedia** [Roboron3042/mastoes-bots#4]
Could the FediTree.py (and I suppose others that fetch user posts) be modified to include more conditions such as not discoverable and do not index for those users that do not know to add a NoBot tag to their profile? FediFetcher has a simple implementation that could help illustrate what I mean.

https://github.com/nanos/FediFetcher/blob/c0dad15a74f1b8c5d65a409bffc081d08bd07fc8/find_posts.py#L120

This is not a big issue, but I'm certain there are folks on fedi that will be unhappy about a 'bot' putting them into a post of something.

**Comment by Roboron3042** [comment]
Afaik the "do not index" is used by the software to avoid displaying the account in search results. I don't see how this is relevant to any of my bots.

But checking for the "discoverable" field does make some sense, at least for FediTree. This is used to control whether your account is showcased by "discovery" algorithms, and you could consider FediTree to be kind of one.

Better handling of the #nobot tag is also required. It does not work if you write #NoBot instead of #nobot for example. It also does nothing if you are the one triggering the bot, which probably should, at least for the bots that are triggered easily such as FediTree and Insultabot.
